### ISSUE TITLE
Include MySQL and PostgreSQL development libraries?

### ISSUE THREAD

**Issue by frenkel** [rails/docked#23]
The Rails `Dockerfile` includes the Debian packges `default-mysql-client` and `postgresql-client`. Should they be included here as well, or is using MySQL and PostgreSQL out of scope for this project?

**Comment by durierem** [comment]
See https://github.com/rails/docked/issues/16

**Comment by subuta** [comment]
https://github.com/docker/compose/issues/8077#issuecomment-1499885440

From docker-compose version "v2.17.2" or earlier (I'm not sure). they added `dockerfile_inline` feature. and that would be a good solution who wants to install additional dependecies which didn't included in "docked(rails/cli)" image if they uses `docker-compose`.

### `docker-compose.yml`

Replace `dockerfile` with `dockerfile_inline` should work.

```yaml
services:
  rails:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/rails/cli
        # Install additional dependencies.
        RUN apt-get update -qq && apt-get install -y default-libmysqlclient-dev libpq-dev
```
